version: '3.9'

services:
  schooldb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3

volumes:
 portainer_data:
 postgres_data:
 pgadmin_data:
 elasticsearch-data:


