CREATE SCHEMA IF NOT EXISTS std AUTHORIZATION admin;

CREATE TABLE std.course (id varchar(36) NOT NULL, name varchar(50) NOT NULL, description varchar(1000) NOT NULL, CONSTRAINT course_pkey PRIMARY KEY (id));
CREATE TABLE std.course_tr (id varchar(36) NOT NULL, language_id varchar(36) NOT NULL, name varchar(50) NOT NULL, description varchar(1000) NOT NULL, CONSTRAINT course_tr_pkey PRIMARY KEY (id));
CREATE TABLE std.enrollment (id varchar(36) NOT NULL, enrollment_date timestamp NOT NULL, grade varchar(10) NOT NULL, course_id varchar(36) NOT NULL, student_id varchar(36) NOT NULL, CONSTRAINT enrollment_pkey PRIMARY KEY (id));
CREATE TABLE std.student (id varchar(36) NOT NULL, nick_name varchar(50) NOT NULL, place_of_birth varchar(50) NOT NULL, date_of_birth date NOT NULL, gender varchar(1) NOT NULL, CONSTRAINT student_pkey PRIMARY KEY (id));
ALTER TABLE std.course_tr ADD CONSTRAINT course_tr_id_fkey FOREIGN KEY (id) REFERENCES std.course (id);
ALTER TABLE std.course_tr ADD CONSTRAINT course_tr_language_id_fkey FOREIGN KEY (language_id) REFERENCES tb_language (id);
ALTER TABLE std.enrollment ADD CONSTRAINT enrollment_course_id_fkey FOREIGN KEY (course_id) REFERENCES std.course (id);
ALTER TABLE std.enrollment ADD CONSTRAINT enrollment_student_id_fkey FOREIGN KEY (student_id) REFERENCES std.student (id);
ALTER TABLE std.student ADD CONSTRAINT student_id_fkey FOREIGN KEY (id) REFERENCES usr."user" (id);


INSERT INTO std.course(id, name, description) VALUES
('kursus-manajemen-daycare', 'Kursus Manajemen Daycare', 'Kursus ini dirancang untuk memberikan pengetahuan dan keterampilan dalam mengelola pusat daycare. Peserta akan mempelajari aspek operasional, manajemen staf, pengelolaan anggaran, dan pembuatan program pembelajaran yang sesuai untuk anak-anak. Fokus pada kepatuhan terhadap regulasi dan standar keselamatan juga menjadi bagian penting dari kursus ini.')
                                                   ,('pelatihan-perawatan-dan-paud', 'Pelatihan Perawatan dan Pengasuhan Anak Usia Dini', 'Kursus ini fokus pada pengembangan keterampilan dalam merawat dan mengasuh anak-anak usia dini di lingkungan daycare. Peserta akan belajar tentang perkembangan fisik, emosional, dan kognitif anak-anak, serta teknik-teknik praktis untuk mendukung perkembangan mereka dalam suasana yang aman dan mendukung.')
                                                   ,('kursus-edukasi-anak-usia-dini', 'Kursus Kreativitas dan Edukasi Anak Usia Dini', 'Kursus ini mengajarkan cara merancang dan mengimplementasikan kegiatan kreatif dan edukatif untuk anak-anak di daycare. Peserta akan mempelajari berbagai metode pengajaran interaktif, termasuk seni, musik, permainan, dan kegiatan luar ruangan yang dirancang untuk merangsang kreativitas dan pembelajaran anak-anak.')
                                                   ,('dasar-pemograman-csharp','Dasar Pemrograman C# dengan .NET','Kursus ini dirancang untuk pemula yang ingin mempelajari dasar-dasar pemrograman dengan bahasa C# di platform .NET. Peserta akan belajar tentang sintaks dasar C#, konsep OOP (Object-Oriented Programming), serta pembuatan aplikasi sederhana menggunakan Visual Studio (Code).')
                                                   ,('restful-api-dotnet','Pengembang RESTful API dengan .NET','Kursus ini dirancang untuk pengembang yang ingin menguasai pembuatan RESTful API menggunakan .NET. Peserta akan mempelajari prinsip-prinsip desain REST, implementasi API yang aman dan efisien, serta integrasi dengan database dan layanan eksternal. Selain itu, kursus ini juga mencakup praktik terbaik dalam dokumentasi API menggunakan Swagger, penanganan kesalahan, serta pengujian API untuk memastikan kinerja dan keandalannya dalam lingkungan produksi.')
                                                   ,('layanan-grpc-dotnet','Pengembangan Layanan gRPC menggunakan .NET','Kursus ini berfokus pada pengembangan layanan gRPC dengan menggunakan .NET. Peserta akan mempelajari dasar-dasar gRPC, termasuk protokol komunikasi berbasis HTTP/2, cara mendefinisikan kontrak layanan dengan Protocol Buffers, serta implementasi klien dan server gRPC. Kursus ini juga mencakup topik-topik lanjutan seperti autentikasi, pengamanan komunikasi, serta pengoptimalan kinerja layanan gRPC di lingkungan produksi. Peserta akan mendapatkan pengalaman praktis dalam membangun layanan yang cepat, efisien, dan skalabel menggunakan .NET.')
                                                   ,('microservices-dotnet','Kursus Pengembangan Microservices dengan .NET','Kursus ini mengajarkan cara membangun arsitektur microservices menggunakan .NET. Peserta akan mempelajari cara membagi aplikasi menjadi layanan-layanan kecil yang independen, penggunaan API Gateway, serta pengelolaan komunikasi antar layanan menggunakan gRPC dan protokol REST.')
                                                   ,('sql-dasar','Dasar-Dasar Structured Query Language (SQL)','Kursus ini memberikan pengantar menyeluruh tentang SQL, bahasa standar untuk mengelola dan memanipulasi database relasional. Peserta akan mempelajari perintah SQL dasar, termasuk SELECT, INSERT, UPDATE, dan DELETE, serta bagaimana membuat dan memodifikasi skema database menggunakan pernyataan CREATE, ALTER, dan DROP. Kursus ini mencakup teknik-teknik kueri, pemfilteran data, pengurutan, dan penggabungan beberapa tabel untuk mengambil dataset yang kompleks. Selain itu, peserta akan mengeksplorasi praktik terbaik untuk menulis kueri SQL yang efisien dan mengatasi masalah umum. Kursus ini ideal bagi mereka yang baru mengenal SQL atau ingin memperkuat pengetahuan dasar mereka dalam manajemen database.')
                                                   ,('sql-lanjutan','Structured Query Language (SQL) Lanjutan','Kursus ini membahas teknik-teknik SQL lanjutan untuk manajemen dan kueri database yang lebih kompleks dan canggih. Peserta akan mempelajari topik seperti subquery, ekspresi tabel umum (CTE), fungsi jendela, dan gabungan lanjutan. Kursus ini juga mencakup teknik-teknik optimasi kinerja, termasuk pembuatan indeks, rencana eksekusi kueri, dan penyetelan. Selain itu, peserta akan mempelajari tentang transaksi, kontrol konkurensi, dan penanganan kesalahan dalam SQL. Kursus ini dirancang bagi mereka yang memiliki pemahaman dasar tentang SQL dan ingin meningkatkan keterampilan mereka untuk menangani kueri yang kompleks dan mengoptimalkan kinerja database.')
;
INSERT INTO std.course_tr(id, language_id, name, description) VALUES
('kursus-manajemen-daycare', 'en', 'Daycare Management Course', 'This course is designed to provide knowledge and skills in managing a daycare center. Participants will learn about operational aspects, staff management, budget management, and creating appropriate learning programs for children. The course also focuses on compliance with regulations and safety standards.')
                                                                   ,('pelatihan-perawatan-dan-paud', 'en', 'Early Childhood Care and Nurturing Training', 'This course focuses on developing skills in caring for and nurturing young children in a daycare environment. Participants will learn about the physical, emotional, and cognitive development of children and practical techniques to support their growth in a safe and supportive environment.')
                                                                   ,('kursus-edukasi-anak-usia-dini', 'en', 'Creativity and Early Childhood Education Course', 'This course teaches how to design and implement creative and educational activities for children in daycare. Participants will learn various interactive teaching methods, including art, music, games, and outdoor activities designed to stimulate creativity and learning in children.')
                                                                   ,('dasar-pemograman-csharp','en','Introduction to C# Programming with .NET','This course is designed for beginners who want to learn the basics of programming with C# on the .NET platform. Participants will learn basic C# syntax, Object-Oriented Programming (OOP) concepts, and how to create simple applications using Visual Studio. (Code)')
                                                                   ,('restful-api-dotnet','en','RESTful API Development with .NET', 'This course is designed for developers who want to master building RESTful APIs using .NET. Participants will learn REST design principles, how to implement secure and efficient APIs, and integration with databases and external services. Additionally, the course covers best practices in API documentation using Swagger, error handling, and API testing to ensure performance and reliability in a production environment.')
                                                                   ,('layanan-grpc-dotnet','en','gRPC Service Development with .NET','This course focuses on developing gRPC services using .NET. Participants will learn the fundamentals of gRPC, including the HTTP/2-based communication protocol, defining service contracts with Protocol Buffers, and implementing gRPC clients and servers. The course also covers advanced topics such as authentication, securing communications, and optimizing gRPC service performance in a production environment. Participants will gain hands-on experience in building fast, efficient, and scalable services with .NET.')
                                                                   ,('microservices-dotnet','en','Microservices Development with .NET','This course teaches how to build microservices architecture using .NET Core. Participants will learn how to break down applications into small, independent services, use an API Gateway, and manage communication between services using gRPC and REST protocols.')
                                                                   ,('sql-dasar','en','Fundamentals of Structured Query Language (SQL)','This course provides a comprehensive introduction to SQL, the standard language for managing and manipulating relational databases. Participants will learn the basic SQL commands, including SELECT, INSERT, UPDATE, and DELETE, as well as how to create and modify database schemas using CREATE, ALTER, and DROP statements. The course covers querying techniques, data filtering, sorting, and joining multiple tables to retrieve complex datasets. Additionally, participants will explore best practices for writing efficient SQL queries and troubleshooting common issues. This course is ideal for those who are new to SQL or want to strengthen their foundational knowledge in database management.')
                                                                   ,('sql-lanjutan','en','Advance Structured Query Language (SQL)','This course delves into advanced SQL techniques for more complex and sophisticated database management and querying. Participants will explore topics such as subqueries, common table expressions (CTEs), window functions, and advanced joins. The course also covers performance optimization techniques, including indexing, query execution plans, and tuning. Additionally, participants will learn about transactions, concurrency control, and error handling in SQL. This course is designed for those who have a foundational understanding of SQL and want to enhance their skills to handle complex queries and optimize database performance.')
;

--insert history update
INSERT INTO public.database_change_log(
    filename, executed_date)
VALUES ('std-initdb.sql', now());    